### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by canzi-teacher** [akaalias/obsidian-footnotes#1]
If there is text on the last line, the generated footnotes will be invalid in preview.
Consider the following code:
if (lastLine.length > 0) {
	if(lastLine.match(detailLineRegex)) {
    	editor.replaceRange(`\n[^${footNoteId}]: `, { line: doc.lineCount(), ch: 0 });
	}else{
		editor.replaceRange(`\n\n[^${footNoteId}]: `, { line: doc.lineCount(), ch: 0 });
	}
}

**Comment by Captain2021** [comment]
hello,a bug
![image](https://user-images.githubusercontent.com/53848822/109444191-9c7bfb80-7a77-11eb-88db-6cee306dcf97.png)

**Comment by akaalias** [comment]
> If there is text on the last line, the generated footnotes will be invalid in preview.
> Consider the following code:
> if (lastLine.length > 0) {
> if(lastLine.match(detailLineRegex)) {
> editor.replaceRange(`\n[^${footNoteId}]: `, { line: doc.lineCount(), ch: 0 });
> }else{
> editor.replaceRange(`\n\n[^${footNoteId}]: `, { line: doc.lineCount(), ch: 0 });
> }
> }

Hi there!

Can you please share a step-by-step description so I can reproduce?

## Bug Template

### Steps to reproduce



### Expected result



### Actual result



### Environment

- Operating system: 

- Obsidian version:


----------

### Additional information

**Comment by akaalias** [comment]
> hello,a bug
> ![image](https://user-images.githubusercontent.com/53848822/109444191-9c7bfb80-7a77-11eb-88db-6cee306dcf97.png)

Hi there and thank you! Can you please share a step-by-step description so I can reproduce?

### Steps to reproduce



### Expected result



### Actual result



### Environment

- Operating system: 

- Obsidian version:


----------

### Additional information

**Comment by Captain2021** [comment]
Hello akaalias:  
First of all, thank you for your reply, and I really like your template for submitting bugs.  
（ I hope you don’t get too entangled in some of my grammatical errors ... ）
# 1. Steps to reproduce
1. downLoad the footnotes plugin 
2. put it in `\.obsidian\plugins` 
3. restart ob
4. find footnotes and open it
# 2. Expected result
like this 
![image](https://user-images.githubusercontent.com/53848822/109588929-7ff9c500-7b44-11eb-9ca6-2b85f1eefb74.png)

# 3. Actual result
when i click this btn，A bug has appeared，it’s can‘t open
![image](https://user-images.githubusercontent.com/53848822/109588946-86883c80-7b44-11eb-864a-a35b28d4affb.png)

# 4. Environment
## 4.1 Operating system:
* win10
* 64 bit
## 4.2 Obsidian version:
obsidian version：v0.11.4

# 5. other 
this may not be your problem,Because other people around me succeeded,only 2~3 person failed(the same bug)  
And other plugins also have this bug ,So i think it maybe a bug of obsidian
![image](https://user-images.githubusercontent.com/53848822/109588858-5e004280-7b44-11eb-9140-c9246ecba1d5.png)

**Comment by akaalias** [comment]
Hi there @Captain2021 !

Thank you for submitting the details, that helps me very much! 

So, just to make sure: 

1. Have you followed the steps to manually install the plugin? 
2. Please note: Downloading the .zip from this repository will NOT work

https://forum.obsidian.md/t/footnote-shortcut/8872/19?u=akaalias

<img width="730" alt="Screenshot 2021-03-02 at 14 28 00" src="https://user-images.githubusercontent.com/111555/109655391-8481a600-7b63-11eb-9081-6563091d1cb4.png">

Let me know and let's hope we can [get the plugin into the directory soon!](https://github.com/obsidianmd/obsidian-releases/pull/185)

**Comment by Captain2021** [comment]
> Hi there @Captain2021 !
> 
> Thank you for submitting the details, that helps me very much!
> 
> So, just to make sure:
> 
> 1. Have you followed the steps to manually install the plugin?
> 2. Please note: Downloading the .zip from most plugin repositories will NOT work because they're missing the `main.js` file.
> 
> https://forum.obsidian.md/t/footnote-shortcut/8872/19?u=akaalias
> 
> <img alt="Screenshot 2021-03-02 at 14 28 00" width="730" src="https://user-images.githubusercontent.com/111555/109655391-8481a600-7b63-11eb-9081-6563091d1cb4.png">
> 
> Let me know and let's hope we can [get the plugin into the directory soon!](https://github.com/obsidianmd/obsidian-releases/pull/185)

hahahah,nice
